version: '3.8'

services:
  discovery-service:
    build:
      context: ./DiscoveryService
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - JAVA_OPTS=-Xmx512m

  auth-service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
    depends_on:
      - discovery-service

  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "8801:8801"
    environment:
      - JAVA_OPTS=-Xmx512m
    depends_on:
      - discovery-service

  product-service:
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    ports:
      - "8802:8802"
    environment:
      - JAVA_OPTS=-Xmx512m
    depends_on:
      - discovery-service

  api-gateway:
    build:
      context: ./API_Gateway
      dockerfile: Dockerfile
    ports:
      - "8803:8803"
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-service
      - auth-service
      - user-service
      - product-service


#
#version: '3.8'
#
#services:
#  discovery-service:
#    build:
#      context: ./DiscoveryService
#      dockerfile: Dockerfile
#    ports:
#      - "8761:8761"
#    environment:
#      - JAVA_OPTS=-Xmx512m
#
#  auth-service:
#    build:
#      context: ./AuthService
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      - JAVA_OPTS=-Xmx512m
#      - SPRING_DATASOURCE_URL=jdbc:mysql://auth-db:3306/authjwt
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=anhdagia
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SPRING_JPA_SHOW_SQL=true
#      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5Dialect
#    depends_on:
#      - discovery-service
#      - auth-db
#
#  user-service:
#    build:
#      context: ./UserService
#      dockerfile: Dockerfile
#    ports:
#      - "8801:8801"
#    environment:
#      - JAVA_OPTS=-Xmx512m
#      - SPRING_DATASOURCE_URL=jdbc:mysql://user-db:3306/userservice
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=rootpassword
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=anhdagia
#      - SPRING_JPA_SHOW_SQL=true
#      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5Dialect
#    depends_on:
#      - discovery-service
#      - user-db
#
#  product-service:
#    build:
#      context: ./ProductService
#      dockerfile: Dockerfile
#    ports:
#      - "8802:8802"
#    environment:
#      - JAVA_OPTS=-Xmx512m
#      - SPRING_DATASOURCE_URL=jdbc:mysql://product-db:3306/productservice
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=anhdagia
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SPRING_JPA_SHOW_SQL=true
#      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5Dialect
#    depends_on:
#      - discovery-service
#      - product-db
#
#  api-gateway:
#    build:
#      context: ./API_Gateway
#      dockerfile: Dockerfile
#    ports:
#      - "8803:8803"
#    environment:
#      - JAVA_OPTS=-Xmx512m
#    depends_on:
#      - discovery-service
#
#  auth-db:
#    image: mysql:8
#    environment:
#      MYSQL_DATABASE: authjwt
#      MYSQL_ROOT_PASSWORD: anhdagia
#    ports:
#      - "3307:3306"  # Changed from 3306 to 3307 to avoid conflict
#    volumes:
#      - auth-db-data:/var/lib/mysql
#
#  user-db:
#    image: mysql:8
#    environment:
#      MYSQL_DATABASE: userservice
#      MYSQL_ROOT_PASSWORD: anhdagia
#    ports:
#      - "3308:3306"  # Changed from 3306 to 3308 to avoid conflict
#    volumes:
#      - user-db-data:/var/lib/mysql
#
#  product-db:
#    image: mysql:8
#    environment:
#      MYSQL_DATABASE: productservice
#      MYSQL_ROOT_PASSWORD: anhdagia
#    ports:
#      - "3309:3306"  # Changed from 3306 to 3309 to avoid conflict
#    volumes:
#      - product-db-data:/var/lib/mysql
#
#volumes:
#  auth-db-data:
#  user-db-data:
#  product-db-data:
