#server:
#  port: 8801
#
#spring:
#  application:
#    name: user-service
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/userservice?useSSL=false
#    username: root
#    password: anhdagia
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-service:8761/eureka/
