spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: AuthService
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**
        - id: ProductService
          uri: http://localhost:8802
          predicates:
            - Path=/api/v2/**
        - id: UserService
          uri: http://localhost:8801
          predicates:
            - Path=/api/v1/**
