server:
  port: 8803

spring:
  application:
    name: API_Gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**
        - id: product-service
          uri: http://localhost:8802
          predicates:
            - Path=/api/v2/**
        - id: user-service
          uri: http://localhost:8801
          predicates:
            - Path=/api/v1/**
      discovery:
        locator:
          enabled: true
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true